package com.bebeplace.bebeplaceapi.common.web

object ErrorCode {
    // 인증 관련 에러 코드
    const val LOGIN_FAILED = "LOGIN_FAILED"
    const val MISSING_AUTHORIZATION = "MISSING_AUTHORIZATION"
    const val TOKEN_REFRESH_FAILED = "TOKEN_REFRESH_FAILED"
    const val INVALID_TOKEN = "INVALID_TOKEN"
    const val EXPIRED_TOKEN = "EXPIRED_TOKEN"
    const val INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    
    // 사용자 관련 에러 코드
    const val USER_NOT_FOUND = "USER_NOT_FOUND"
    const val USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    const val INVALID_USER_STATUS = "INVALID_USER_STATUS"
    const val EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    const val NICKNAME_ALREADY_EXISTS = "NICKNAME_ALREADY_EXISTS"
    
    // 유효성 검증 에러 코드
    const val VALIDATION_ERROR = "VALIDATION_ERROR"
    const val INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
    const val INVALID_PASSWORD_FORMAT = "INVALID_PASSWORD_FORMAT"
    const val INVALID_PHONE_FORMAT = "INVALID_PHONE_FORMAT"
    
    // 비즈니스 로직 에러 코드
    const val BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"
    const val RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    const val OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED"
    const val DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
    
    // 시스템 에러 코드
    const val INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    const val DATABASE_ERROR = "DATABASE_ERROR"
    const val EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    const val NETWORK_ERROR = "NETWORK_ERROR"
    
    // 아기 관련 에러 코드
    const val BABY_NOT_FOUND = "BABY_NOT_FOUND"
    const val INVALID_BABY_DATA = "INVALID_BABY_DATA"
    const val MAX_BABIES_EXCEEDED = "MAX_BABIES_EXCEEDED"
    
    // 지역 관련 에러 코드
    const val REGION_NOT_FOUND = "REGION_NOT_FOUND"
    const val INVALID_REGION_DATA = "INVALID_REGION_DATA"
    const val MAX_REGIONS_EXCEEDED = "MAX_REGIONS_EXCEEDED"
    const val DUPLICATE_REGION = "DUPLICATE_REGION"
}