spring:
  datasource:
    url: jdbc:h2:mem:bebeplace
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  flyway:
    enabled: false

jwt:
  secret: mySecretKey1234567890123456789012345678901234567890
  expiration: 86400000 # 24시간 (밀리초)

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# CoolSMS 설정 (개발용 더미값)
coolsms:
  from: 01000000000
  api:
    key: dev-key
    secret: dev-secret
